// Request identifiers are generated by the server, never supplied by callers.
// Accept its random ID and its entropy-failure fallback; reject arbitrary text.
export function validRequestId(value: unknown): string | undefined {
  return typeof value === 'string' && /^(?:[0-9a-f]{32}|[0-9a-f]{1,16}-[0-9a-f]{1,16})(?![\s\S])/u.test(value) ? value : undefined
}

const errorMessages: Readonly<Record<string, string>> = {
  client_update_required: '当前页面版本已过期，请刷新页面后重试。',
  disk_space_low: '服务器可用磁盘空间不足，本次写入未完成。请联系管理员释放磁盘空间；之后刷新并查看任务状态，再重试。',
  disk_usage_unavailable: '暂时无法读取服务器可用磁盘空间，存储用量信息不完整。请稍后刷新存储页；若持续发生，请联系管理员并提供请求编号。',
  global_revision_conflict: '云盘已发生变化，请刷新后重试。',
  idempotency_conflict: '操作请求与已有记录不一致，系统已拒绝本次重复提交。请刷新相关目录或回收站，核对当前状态后再重新发起操作。',
  internal_error: '服务器暂时出了问题，请稍后重试。若问题持续，请提供请求编号。',
  invalid_credentials: '用户名或密码不正确。',
  invalid_encrypted_index: '目录密文格式无效或不受支持，操作已停止。请刷新页面后重新读取目录；若再次发生，请提供请求编号。',
  invalid_idempotency_key: '操作请求未通过校验，本次操作尚未提交。请刷新页面后重新执行；若持续发生，请提供请求编号。',
  invalid_member: '回收站成员请求无效，本次操作未提交。请刷新页面后重新选择项目；若持续发生，请提供请求编号。',
  invalid_object_headers: '上传请求信息无效，文件未保存。请刷新页面后重新选择原文件上传；若持续发生，请提供请求编号。',
  invalid_request: '请求内容无效或格式不符合要求，本次操作未提交。请检查输入并刷新后重试；若持续发生，请提供请求编号。',
  invalid_reservation: '上传预留请求无效，本次任务的预留空间未调整。请刷新页面后重新发起上传；若持续发生，请提供请求编号。',
  invalid_root_index: '首次设置数据未通过校验，云盘尚未初始化。请刷新后重新设置；若持续发生，请联系管理员并提供请求编号。',
  invalid_session: '会话已失效，请重新登录。',
  invalid_trash_index: '首次设置中的回收站数据未通过校验。请刷新后重新设置；若持续发生，请联系管理员并提供请求编号。',
  invalid_vault_config: '云盘配置无效，无法继续操作。请刷新页面；若问题持续，请联系管理员并提供请求编号。',
  maintenance_in_progress: '服务器正在执行维护，此次更改未提交。请稍后刷新并重试。',
  maintenance_metadata_limit: '本次目录更改涉及内容过多，未提交。请缩小操作范围后重试。',
  maintenance_reserve_exhausted: '元数据维护预留不足，本次删除或覆盖未提交，原项目仍在原位。可尝试永久清空回收站后刷新存储用量；若预留仍不足或无法清理，请联系管理员检查维护预留配置。取消普通上传不会增加这项预留。',
  metadata_object_too_large: '目录规模超过可安全保存的上限。请拆分目录后重试。',
  metadata_revision_conflict: '目录或回收站内容已发生变化，本次操作未提交。请刷新相关页面并重新确认操作。',
  metadata_tombstoned: '此目录已移入回收站。请返回活动目录后重试。',
  method_not_allowed: '此操作当前不可用。请刷新页面后重试；若持续发生，请提供请求编号。',
  not_found: '请求的数据或操作目标不存在，可能已发生变化。请刷新相关页面并检查当前内容。',
  object_conflict: '云盘对象状态已变化，本次操作未提交。请刷新相关目录或传输面板后重试；若是上传，请重新选择原文件。若持续发生，请提供请求编号。',
  object_digest_mismatch: '上传数据未通过完整性校验，文件未提交。请刷新页面后重新选择原文件上传；若再次发生，请提供请求编号。',
  object_length_header_mismatch: '上传请求声明的长度不一致，文件未保存。请刷新页面后重新选择原文件上传；若持续发生，请提供请求编号。',
  object_not_activated: '上传对象尚未就绪，目录更改未提交。请刷新传输面板检查任务状态后再重试。',
  object_receive_in_progress: '此上传对象仍在处理中。请等待当前任务结束后刷新传输面板。',
  object_size_exceeded: '上传数据超出请求声明长度，文件未保存。请刷新页面后重新选择原文件上传；若持续发生，请提供请求编号。',
  object_size_mismatch: '上传未完整接收，文件尚未提交。请检查网络后从传输面板继续，或重新选择原文件。',
  object_unavailable: '文件数据或上传对象当前不可用。请刷新目录或传输面板核对状态后再操作；若持续发生，请提供请求编号。',
  origin_rejected: '安全来源校验未通过。请从当前打开的 XDrive 页面重新操作。',
  quota_exceeded: '空间配额或维护预留不足，本次操作未完成。请在存储页查看用量；若是首次设置或清理后仍无法继续，请联系管理员并提供请求编号。',
  rate_limited: '尝试过于频繁，请稍后重试。',
  receive_deadline_unavailable: '服务器暂时无法安全接收请求，请稍后重试；若持续发生，请提供请求编号。',
  release_changed: 'GitHub 最新稳定版已变化，本次尚未安装。请重新检查更新后重试。',
  release_check_failed: '无法连接 GitHub 获取稳定版信息，本次更新未启动。请检查服务器网络后重试。',
  reservation_in_use: '上传任务仍有数据正在处理。请等待当前任务结束后刷新传输面板。',
  service_closing: '服务器正在关闭或重启。请等待服务恢复后重试。',
  setup_conflict: '首次设置发生冲突，尚未完成。请刷新页面查看当前状态；若仍显示未初始化，可重新提交，持续失败时请联系管理员并提供请求编号。',
  setup_unavailable: '首次设置入口当前不可用，设置链接可能无效、已过期或设置已完成。请刷新确认账号状态；若仍显示未初始化，请联系管理员重新生成设置链接。',
  storage_unavailable: '文件存储暂时不可用，此操作未完成。请稍后重试；若持续发生，请提供请求编号。',
  tombstone_build_unavailable: '回收站内容已变化或暂不可用。请刷新回收站并重新选择项目。',
  tombstone_member_unavailable: '所选回收站内容已变化。请刷新回收站后重新操作。',
  tombstone_overlap: '回收站所选内容重叠或已变化。请刷新列表并重新选择要操作的项目。',
  tombstone_unavailable: '回收站项目已发生变化。请刷新回收站后重试。',
  unauthorized: '会话已失效，请重新登录。',
  invalid_update_request: '更新请求未通过校验，本次更新尚未启动。请重新检查更新后再试。',
  update_already_queued: '更新请求已排队，请等待当前更新结束后刷新状态。',
  update_manager_unavailable: '服务器更新管理服务未启用或未运行。请联系管理员启用 xdrive-web-update.path 后重试。',
  update_queue_unavailable: '服务器更新请求队列暂不可用，本次更新未启动。请联系管理员检查更新服务。',
  update_status_not_found: '找不到此更新任务状态。请重新检查更新；若问题持续，请联系管理员。',
  object_not_found: '文件数据不可用，请刷新后重试。',
  upload_expired: '上传任务已过期，请重新选择原文件上传。',
  upload_receive_timeout: '上传接收超时，未完成对象已清理；请检查网络后从传输面板重新选择原文件继续。',
  upload_state_mismatch: '上传任务状态已变化。请刷新传输面板，再选择继续或重新上传。',
  upload_state_too_large: '上传任务记录超过服务端安全读取上限，暂时无法判断当前任务是否完整提交。请刷新云盘核对目标文件；若仍需恢复，请联系管理员并提供请求编号。',
  upload_unavailable: '上传任务不存在或已过期。请重新选择原文件开始上传。',
  vault_config_conflict: 'Vault 配置已变化，请重新登录。',
  vault_config_invalid: 'Vault 配置无法读取。请联系管理员并提供请求编号。',
  vault_mutation_conflict: '云盘已发生变化，请刷新后重试。',
  vault_not_found: '云盘尚未完成设置或当前状态不可用。请刷新页面；若持续发生，请联系管理员并提供请求编号。',
  web_assets_unavailable: '页面资源暂不可用。请刷新页面重试；若问题持续，请联系管理员并提供请求编号。',
}

function errorMessage(status: number, code: string): string {
  return Object.hasOwn(errorMessages, code) ? errorMessages[code]! : status >= 500 ? '服务器暂时出了问题，请稍后重试。' : '请求未能完成，请刷新后重试。'
}

export class APIError extends Error {
  readonly status: number
  readonly code: string
  readonly shortfallBytes?: number
  readonly requestId?: string

  constructor(status: number, code: string, shortfallBytes?: number, requestId?: string) {
    const safeCode = /^[a-z][a-z0-9_]{0,63}(?![\s\S])/u.test(code) ? code : 'request_failed'
    super(errorMessage(status, safeCode))
    this.name = 'APIError'
    this.status = status
    this.code = safeCode
    this.shortfallBytes = shortfallBytes
    this.requestId = validRequestId(requestId)
  }
}

export async function parseAPIError(response: Response): Promise<APIError> {
  let code = 'request_failed', shortfallBytes: number | undefined
  const headerId = validRequestId(response.headers.get('X-Request-ID'))
  let requestId = headerId
  try {
    const value: unknown = await response.json()
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      const body = value as Record<string, unknown>
      if (typeof body.error === 'string') code = body.error
      if (Number.isSafeInteger(body.shortfallBytes) && Number(body.shortfallBytes) >= 0) shortfallBytes = Number(body.shortfallBytes)
      if ('requestId' in body) {
        const bodyId = validRequestId(body.requestId)
        // Never associate an error with an unrelated header/body identifier.
        requestId = bodyId && (!headerId || bodyId === headerId) ? bodyId : undefined
      }
    }
  } catch {
    // Non-JSON proxy errors still carry a usable server header, when present.
  }
  return new APIError(response.status, code, shortfallBytes, requestId)
}
