import { expect, test } from '@playwright/test'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { startIsolatedServer } from './isolated-server'
import AxeBuilder from '@axe-core/playwright'

test('server backup warning caps browser preferences and all views use actual completed backup time', async ({ page }) => {
  test.setTimeout(120_000)
  const server = await startIsolatedServer({ backupWarnAfterDays: 2 })
  const backup = mkdtempSync(join(tmpdir(), 'xdrive-warning-backup-'))
  try {
    // Fixed page time is three days ahead; this is clock simulation, not wall-clock aging.
    await page.clock.setFixedTime(new Date(Date.now() + 3 * 86400000))
    await page.addInitScript(() => localStorage.setItem('xdrive.preferences.v1', JSON.stringify({ backupReminderDays: 90 })))
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill('correct horse battery')
    await page.getByLabel('再次输入密码').fill('correct horse battery')
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible({ timeout: 30_000 })
    await expect(page.getByRole('note', { name: '备份提醒' })).toContainText('尚无已完成的备份')
    server.backupTo(backup)
    const nav = page.getByRole('navigation', { name: '主导航' })
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    const storage = page.getByRole('region', { name: '存储空间详情' })
    await expect(storage.locator('time')).toBeVisible()
    await expect(storage).toContainText('上次备份已超过 2 天')
    await expect(page.getByRole('note', { name: '备份提醒' })).toContainText('上次备份已超过 2 天')
    const usage = await page.evaluate(async () => (await (await fetch('/api/v1/storage/usage')).json()))
    expect(usage.backupWarnAfterDays).toBe(2)
    expect(Math.abs(Date.now() - usage.lastBackupAt)).toBeLessThan(30_000)
    await nav.getByRole('button', { name: '设置', exact: true }).click()
    const settings = page.getByRole('region', { name: '云盘设置' })
    await expect(page.getByLabel('备份提醒阈值', { exact: true })).toHaveValue('90')
    await expect(settings).toContainText('服务器阈值 2 天，实际阈值 2 天')
    await expect(settings).toContainText('上次备份已超过 2 天')
    await page.evaluate(() => window.xdrivePreferences.set({ backupReminderDays: 1 }))
    await expect(settings).toContainText('服务器阈值 2 天，实际阈值 1 天')
    await expect(settings).toContainText('上次备份已超过 1 天')
    await expect(page.getByRole('note', { name: '备份提醒' })).toContainText('上次备份已超过 1 天')
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(storage).toContainText('上次备份已超过 1 天')
  } finally { await server.close(); rmSync(backup, { recursive: true, force: true }) }
})

test('backup guidance traps/restores focus, dismissal stays in memory and re-entry reminds again', async ({ page }) => {
  test.setTimeout(120_000)
  const server = await startIsolatedServer()
  try {
    await page.clock.install()
    await page.setViewportSize({ width: 320, height: 700 })
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill('correct horse battery')
    await page.getByLabel('再次输入密码').fill('correct horse battery')
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible({ timeout: 30_000 })
    const snapshot = () => page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }))
    await page.locator('input[type="file"]:not([webkitdirectory])').first().setInputFiles({ name: 'dialog-selection.txt', mimeType: 'text/plain', buffer: Buffer.from('encrypted keyboard fixture') })
    await expect(page.getByRole('button', { name: 'dialog-selection.txt', exact: true })).toBeVisible()
    const before = await snapshot()
    const notice = page.getByRole('note', { name: '备份提醒' })
    const help = notice.getByRole('button', { name: '了解如何备份' })
    await help.click()
    const dialog = page.getByRole('dialog', { name: '如何备份 XDrive' })
    const close = dialog.getByRole('button', { name: '关闭备份说明' })
    await expect(close).toBeFocused()
    await expect(dialog).toContainText('xdrive backup --verify')
    await expect(dialog).toContainText('VPS 之外')
    const audit = await new AxeBuilder({ page }).include('.backup-help-dialog').analyze()
    expect(audit.violations.filter(issue => ['serious', 'critical'].includes(issue.impact!))).toEqual([])
    await page.keyboard.press('Tab')
    await expect(close).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(close).toBeFocused()
    await page.keyboard.press('Control+a')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(help).toBeFocused()
    await expect(page.getByText('已选 1 项', { exact: true })).toHaveCount(0)
    await help.click()
    await close.click()
    await expect(help).toBeFocused()
    await notice.getByRole('button', { name: '本次关闭备份提醒' }).click()
    await expect(notice).toHaveCount(0)
    expect(await snapshot()).toEqual(before)
    await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(page.getByRole('region', { name: '存储空间详情' })).toContainText('从未备份')
    await expect(notice).toHaveCount(0)
    await page.reload()
    await expect(page.getByRole('heading', { name: '重新解锁云盘' })).toBeVisible()
    await page.getByLabel('密码', { exact: true }).fill('correct horse battery')
    await page.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(notice).toBeVisible()
    await notice.getByRole('button', { name: '了解如何备份' }).click()
    await expect(dialog).toBeVisible()
    await page.clock.fastForward(11 * 60_000)
    await expect(page.getByRole('heading', { name: '重新解锁云盘' })).toBeVisible()
    await expect(dialog).toHaveCount(0)
    await expect(notice).toHaveCount(0)
  } finally { await server.close() }
})
