import { expect, test } from './legacy-list-test'
import { startIsolatedServer } from './isolated-server'

for (const mobile of [false, true]) test(`folded encrypted folder paths preserve navigation, keyboard and lock privacy (${mobile ? 'mobile' : 'desktop'})`, async ({ page }, testInfo) => {
  test.setTimeout(90000)
  if (mobile) await page.setViewportSize({ width: 390, height: 844 })
  const server = await startIsolatedServer()
  const names = ['私密第一层', '私密第二层', '私密第三层', '私密第四层', '很长的当前目录名称用于验证手机路径不会横向溢出'.repeat(2)]
  const urls: string[] = []
  try {
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill('correct horse battery')
    await page.getByLabel('再次输入密码').fill('correct horse battery')
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
    const path = page.getByRole('navigation', { name: '文件夹路径', exact: true })
    for (const [index, name] of names.entries()) {
      await expect(page.getByRole('button', { name: '新建文件夹', exact: true })).toBeEnabled()
      page.once('dialog', dialog => void dialog.accept(name))
      await page.getByRole('button', { name: '新建文件夹', exact: true }).click()
      await expect(page.getByRole('status')).toContainText('文件夹已创建。')
      await page.getByRole('button', { name, exact: true }).click()
      await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
      await expect(page.getByRole('button', { name: '上传', exact: true })).toBeEnabled()
      urls.push(page.url())
      if (index < 2) await expect(path.getByText('…', { exact: true })).toHaveCount(0)
      else await expect(path.getByText('…', { exact: true })).toBeVisible()
    }
    await expect(path.locator('[aria-current="page"]')).toHaveText(names.at(-1)!)
    await expect(path.getByLabel('当前目录 0 项', { exact: true })).toBeVisible()
    expect(await page.title()).toBe('XDrive')
    expect(page.url()).toMatch(/\/drive\/[A-Za-z0-9_-]{16,64}$/)
    expect(await page.evaluate(() => JSON.stringify(history.state))).not.toContain('私密')
    const toggle = path.getByText('…', { exact: true })
    await toggle.focus()
    await page.keyboard.press('ArrowDown')
    const first = path.getByRole('button', { name: names[0], exact: true })
    await expect(first).toBeFocused()
    await page.keyboard.press('End')
    await expect(path.getByRole('button', { name: names[2], exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(toggle).toBeFocused()
    await expect(first).not.toBeVisible()
    await toggle.click()
    await expect(first).toBeVisible()
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }))
    expect(overflow.scroll).toBeLessThanOrEqual(overflow.width)
    await page.screenshot({ path: testInfo.outputPath('folded-path.png') })
    await first.click()
    await expect(page).toHaveURL(urls[0])
    await expect(page.getByRole('button', { name: names[1], exact: true })).toBeVisible()
    await expect(toggle).toHaveCount(0)
    await path.getByRole('button', { name: '我的文件', exact: true }).click()
    await expect(page).toHaveURL(`${server.baseURL}/drive`)
    await expect(page.getByRole('button', { name: names[0], exact: true })).toBeVisible()
    await page.getByRole('button', { name: names[0], exact: true }).click()
    for (const name of names.slice(1)) {
      await page.getByRole('button', { name, exact: true }).click()
      await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
      await expect(page.getByRole('button', { name: '上传', exact: true })).toBeEnabled()
    }
    await toggle.click()
    await expect(first).toBeVisible()
    await page.getByRole('button', { name: '锁定云盘', exact: true }).click()
    await expect(page.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    await expect(page.locator('.breadcrumbs')).toHaveCount(0)
    await expect(page.locator('body')).not.toContainText('私密')
    await expect(page.locator('body')).not.toContainText(names.at(-1)!)
  } finally { await server.close() }
})
