import { expect, test, type Page } from './legacy-list-test'
import { startIsolatedServer } from './isolated-server'
const password = 'correct horse battery'
async function folder(page: Page, name: string) {
  page.once('dialog', dialog => void dialog.accept(name))
  await page.getByRole('button', { name: '新建文件夹', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('文件夹已创建。')
  await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '上传', exact: true })).toBeEnabled()
}

test('opaque nested folder URLs survive refresh, unlock and browser history without private history state', async ({ page }) => {
  const server = await startIsolatedServer()
  let release = () => {}
  try {
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill(password)
    await page.getByLabel('再次输入密码').fill(password)
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
    await folder(page, '私密父目录')
    await expect(page).toHaveURL(/\/drive\/[A-Za-z0-9_-]{16,64}$/)
    const parent = page.url()
    await folder(page, '私密子目录')
    await expect.poll(() => page.url()).not.toBe(parent)
    const child = page.url()
    await page.locator('input[type="file"]:not([webkitdirectory])').first().setInputFiles({ name: 'only-child.txt', mimeType: 'text/plain', buffer: Buffer.from('nested encrypted route fixture') })
    await expect(page.getByRole('status')).toContainText('上传完成。')
    expect(await page.title()).toBe('XDrive')
    expect(await page.evaluate(() => JSON.stringify(history.state))).not.toMatch(/私密|only-child/)
    await page.reload()
    await expect(page.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    await expect(page.locator('body')).not.toContainText('私密')
    await page.getByLabel('密码', { exact: true }).fill(password)
    await page.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(page).toHaveURL(child)
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toBeVisible()
    await expect(page.locator('.breadcrumbs')).toContainText('私密父目录')
    await expect(page.locator('.breadcrumbs')).toContainText('私密子目录')
    await page.goBack()
    await expect(page).toHaveURL(parent)
    await expect(page.getByRole('button', { name: '私密子目录', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toHaveCount(0)
    await page.goForward()
    await expect(page).toHaveURL(child)
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toBeVisible()
    await page.locator('.breadcrumbs').getByRole('button', { name: '私密父目录', exact: true }).click()
    await expect(page).toHaveURL(parent)
    await expect(page.getByRole('button', { name: '私密子目录', exact: true })).toBeVisible()
    await page.locator('.breadcrumbs').getByRole('button', { name: '我的文件', exact: true }).click()
    await expect(page).toHaveURL(`${server.baseURL}/drive`)
    await expect(page.getByRole('button', { name: '私密父目录', exact: true })).toBeVisible()
    // A copied bare URL has no ancestor hint and must resolve from the active root.
    await page.goto(child)
    await expect(page.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    await page.getByLabel('密码', { exact: true }).fill(password)
    await page.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toBeVisible()
    expect(await page.evaluate(() => history.state?.usr ?? null)).toBeNull()
    await page.goto(`${server.baseURL}/drive/unknown-directory-0123456789`)
    await expect(page.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    await page.getByLabel('密码', { exact: true }).fill(password)
    await page.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('回收站')
    await expect(page.getByRole('button', { name: '上传', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: '新建文件夹', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toHaveCount(0)
    await page.locator('.breadcrumbs').getByRole('button', { name: '我的文件', exact: true }).click()
    await expect(page.getByRole('button', { name: '私密父目录', exact: true })).toBeVisible()
    let reached!: () => void, handled!: () => void
    const waiting = new Promise<void>(resolve => { reached = resolve })
    const finished = new Promise<void>(resolve => { handled = resolve })
    const gate = new Promise<void>(resolve => { release = resolve })
    await page.route(`**/api/v1/metadata/${parent.split('/').at(-1)}`, async route => {
      const response = await route.fetch()
      reached(); await gate
      await route.fulfill({ response }).catch(() => undefined)
      handled()
    })
    await page.getByRole('button', { name: '私密父目录', exact: true }).click()
    await waiting
    await expect(page.getByRole('status')).toContainText('正在读取文件夹')
    await page.getByRole('button', { name: '锁定云盘', exact: true }).click()
    await expect(page.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    release(); await finished
    await expect(page.locator('body')).not.toContainText('私密')
    await expect(page.getByRole('button', { name: 'only-child.txt', exact: true })).toHaveCount(0)
    expect(page.workers()).toHaveLength(0)
  } finally { release(); await server.close() }
})
