import { expect, test } from './legacy-list-test'
import { startIsolatedServer } from './isolated-server'

test('another tab renaming, moving and trashing the open folder revalidates its path and disables stale writes', async ({ page, context }) => {
  const server = await startIsolatedServer()
  const other = await context.newPage()
  try {
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill('correct horse battery')
    await page.getByLabel('再次输入密码').fill('correct horse battery')
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
    page.once('dialog', dialog => void dialog.accept('original-parent'))
    await page.getByRole('button', { name: '新建文件夹', exact: true }).click()
    await page.getByRole('button', { name: 'original-parent', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'original-parent', exact: true })).toBeVisible()
    await page.locator('input[type="file"]:not([webkitdirectory])').first().setInputFiles({ name: 'private-child.txt', mimeType: 'text/plain', buffer: Buffer.from('real encrypted cross-tab child') })
    await expect(page.getByRole('status')).toContainText('上传完成。')
    const originalURL = page.url()
    await other.goto(`${server.baseURL}/login`)
    await expect(other.getByRole('heading', { name: '重新解锁云盘', exact: true })).toBeVisible()
    await other.getByLabel('密码', { exact: true }).fill('correct horse battery')
    await other.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(other.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
    other.once('dialog', dialog => void dialog.accept('destination'))
    await other.getByRole('button', { name: '新建文件夹', exact: true }).click()
    await expect(other.getByRole('button', { name: 'destination', exact: true })).toBeVisible()
    other.once('dialog', dialog => void dialog.accept('renamed-parent'))
    await other.getByRole('button', { name: '重命名 original-parent', exact: true }).click()
    await expect(other.getByRole('button', { name: 'renamed-parent', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'renamed-parent', exact: true })).toBeVisible()
    await expect(page).toHaveURL(originalURL)
    await expect(page.getByRole('button', { name: 'private-child.txt', exact: true })).toBeVisible()
    await other.getByRole('checkbox', { name: '选择 renamed-parent', exact: true }).check()
    await other.getByRole('button', { name: '批量移动', exact: true }).click()
    const move = other.getByRole('dialog', { name: '移动 renamed-parent', exact: true })
    await move.getByRole('button', { name: 'destination', exact: true }).click()
    await move.getByRole('button', { name: '移动到此文件夹', exact: true }).click()
    await expect(move).toHaveCount(0)
    await expect(page.locator('.breadcrumbs')).toContainText('destination')
    await expect(page.locator('.breadcrumbs')).toContainText('renamed-parent')
    await expect(page).toHaveURL(originalURL)
    await other.getByRole('button', { name: 'destination', exact: true }).click()
    await expect(other.getByRole('heading', { name: 'destination', exact: true })).toBeVisible()
    other.once('dialog', dialog => void dialog.accept())
    await other.getByRole('button', { name: '移到回收站 renamed-parent', exact: true }).click()
    await expect(other.getByRole('button', { name: 'renamed-parent', exact: true })).toHaveCount(0)
    await expect(page.getByRole('alert')).toContainText('回收站')
    await expect(page.getByRole('button', { name: '上传', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: '新建文件夹', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: 'private-child.txt', exact: true })).toHaveCount(0)
    await page.locator('.breadcrumbs').getByRole('button', { name: '我的文件', exact: true }).click()
    await expect(page.getByRole('button', { name: 'destination', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: '上传', exact: true })).toBeEnabled()
    expect(await page.title()).toBe('XDrive')
  } finally { await other.close(); await server.close() }
})
