import { expect, test } from './legacy-list-test'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import AxeBuilder from '@axe-core/playwright'
import { startIsolatedServer } from './isolated-server'

test('storage route observes real encrypted pending/committed/trash states, fresh backup milliseconds and authenticated refresh', async ({ page, browserName }) => {
  test.setTimeout(120_000)
  const server = await startIsolatedServer(), backup = mkdtempSync(join(tmpdir(), 'xdrive-storage-backup-'))
  let release = () => {}
  try {
    await page.goto(`${server.baseURL}/setup#${server.token}`)
    await page.getByLabel('设置密码').fill('correct horse battery')
    await page.getByLabel('再次输入密码').fill('correct horse battery')
    await page.getByLabel('我已了解：如果忘记密码，云盘数据无法恢复。').check()
    await page.getByRole('button', { name: '创建加密云盘' }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible({ timeout: 30_000 })
    const usage = () => page.evaluate(async () => (await (await fetch('/api/v1/storage/usage')).json()))
    const nav = page.getByRole('navigation', { name: '主导航' })
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(page).toHaveURL(`${server.baseURL}/storage`)
    const screen = page.getByRole('region', { name: '存储空间详情' })
    const pending = screen.locator('dt').filter({ hasText: /^其中未完成上传$/u }).locator('..').locator('dd')
    await expect(pending).toHaveText('0 B')
    await expect(screen).toContainText('从未备份。')
    await expect(screen.getByRole('button', { name: /前往回收站清理/u })).toHaveCount(0)
    await page.evaluate(() => history.back())
    await expect(page).toHaveURL(`${server.baseURL}/drive`)
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
    await page.evaluate(() => history.forward())
    await expect(page).toHaveURL(`${server.baseURL}/storage`)
    await expect(pending).toHaveText('0 B')
    const baseline = await usage()
    await nav.getByRole('button', { name: '我的文件', exact: true }).click()
    let reached = () => {}
    const waiting = new Promise<void>((resolve) => { reached = resolve })
    const held = new Promise<void>((resolve) => { release = resolve })
    await page.route('**/api/v1/metadata/transactions', async (route) => { reached(); await held; await route.continue() })
    await expect(page.getByRole('button', { name: '\u4e0a\u4f20', exact: true })).toBeEnabled()
    await page.locator('input[type="file"]:not([webkitdirectory])').first().setInputFiles({ name: 'storage.txt', mimeType: 'text/plain', buffer: Buffer.from('real encrypted storage sample') })
    await waiting
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(pending).not.toHaveText('0 B')
    const inProgress = await usage()
    expect(inProgress.pendingBytes).toBeGreaterThan(0)
    expect(inProgress.usedBytes).toBe(baseline.usedBytes + inProgress.pendingBytes)
    expect(inProgress.availableBytes).toBe(inProgress.quotaBytes - inProgress.usedBytes - inProgress.reservedBytes)
    expect(inProgress.freeDiskBytes).toBeGreaterThan(0)
    release()
    await expect(page.getByRole('status')).toContainText('上传完成。')
    await screen.getByRole('button', { name: '刷新用量' }).click()
    await expect(pending).toHaveText('0 B')
    expect((await usage()).uploadReservedBytes).toBe(0)
    await page.unroute('**/api/v1/metadata/transactions')
    await nav.getByRole('button', { name: '我的文件', exact: true }).click()
    page.once('dialog', (dialog) => void dialog.accept())
    await page.getByRole('button', { name: '移到回收站 storage.txt' }).click()
    await expect(page.getByRole('button', { name: 'storage.txt', exact: true })).toHaveCount(0)
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(screen.getByRole('button', { name: /前往回收站清理/u })).toBeVisible()
    const trashed = await usage(); expect(trashed.trashBytes).toBeGreaterThan(0)
    await screen.getByRole('button', { name: /前往回收站清理/u }).click()
    await expect(page).toHaveURL(`${server.baseURL}/trash`)
    page.once('dialog', (dialog) => void dialog.accept())
    await page.getByRole('button', { name: '永久删除 storage.txt' }).click()
    await expect(page.getByRole('button', { name: 'storage.txt', exact: true })).toHaveCount(0)
    await nav.getByRole('button', { name: '存储空间', exact: true }).click()
    await expect(screen.getByRole('button', { name: /前往回收站清理/u })).toHaveCount(0)
    expect((await usage()).trashBytes).toBe(0)
    server.backupTo(backup)
    await screen.getByRole('button', { name: '刷新用量' }).click()
    await expect(screen.locator('time')).toBeVisible()
    const backedUp = await usage()
    expect(Math.abs(Date.now() - backedUp.lastBackupAt)).toBeLessThan(30_000)
    await expect(screen).not.toContainText('上次备份已超过 30 天')
    await expect(page.getByRole('note', { name: '备份提醒' })).toHaveCount(0)
    await page.route('**/api/v1/storage/usage', (route) => route.abort('failed'))
    await screen.getByRole('button', { name: '刷新用量' }).click()
    await expect(screen.getByRole('alert')).toContainText('下方为上次读取的用量')
    await expect(screen.locator('time')).toBeVisible()
    await page.unroute('**/api/v1/storage/usage')
    await screen.getByRole('button', { name: '刷新用量' }).click()
    await expect(screen.getByRole('alert')).toHaveCount(0)
    await page.reload()
    await page.getByLabel('密码', { exact: true }).fill('correct horse battery')
    await page.getByRole('button', { name: '解锁云盘', exact: true }).click()
    await expect(page.getByRole('heading', { name: '存储空间', exact: true })).toBeVisible()
    await expect(screen.locator('time')).toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const refreshButton = screen.getByRole('button', { name: '刷新用量' })
    expect(await refreshButton.evaluate((button) => parseFloat(getComputedStyle(button).fontSize))).toBeGreaterThanOrEqual(13)
    const refreshBounds = await refreshButton.boundingBox()
    expect(refreshBounds!.height).toBeGreaterThanOrEqual(44)
    expect(refreshBounds!.width).toBeGreaterThanOrEqual(44)
    const audit = await new AxeBuilder({ page }).include('section[aria-label="存储空间详情"]').analyze()
    expect(audit.violations.filter((issue) => issue.impact === 'critical' || issue.impact === 'serious')).toEqual([])
    const artifacts = join(import.meta.dirname, '..', '..', 'docs', 'operations', 'artifacts', 'storage-2026-09-30', browserName)
    mkdirSync(artifacts, { recursive: true })
    await page.screenshot({ path: join(artifacts, 'mobile.png'), fullPage: true })
    writeFileSync(join(artifacts, 'accessibility.json'), JSON.stringify({ viewport: { width: 390, height: 844 }, browser: `Playwright ${browserName}; not a phone device`, violations: audit.violations }, null, 2))
    await page.getByRole('button', { name: '锁定云盘' }).click()
    await expect(screen).toHaveCount(0)
  } finally { release(); await server.close(); rmSync(backup, { recursive: true, force: true }) }
})
